name: portfolio
description: A dynamic, responsive portfolio website for a Flutter Developer.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Core & Backend ---
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0

  # --- UI & Design ---
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0

  # --- Utilities ---
  url_launcher: ^6.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#1E1E1E"
  image: assets/images/profile.png
  color_dark: "#1E1E1E"
  image_dark: assets/images/profile.png

  android: true
  ios: true
  web: true